[package]
name = "boringos"
version = "0.1.0"
authors = ["Tim Schuster <mail@timschuster.info>"]

[dependencies]
bootloader = "0.3.0"
volatile = "0.2.3"
spin = "0.4.6"
uart_16550 = "0.1.0"
x86_64 = "0.2.8"
slabmalloc = "0.3.0"
static_assertions = "0.2.5"
bitflags = "1.0.4"
raw-cpuid = "6.0.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.log]
version = "0.4.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.cargo-xbuild]
memcpy = true

[patch.crates-io]
slabmalloc = { git = 'https://github.com/gz/rust-slabmalloc/' }