[package]
name = "boringos"
version = "0.1.0"
authors = ["Tim Schuster <mail@timschuster.info>"]

[dependencies]
bootloader = "0.3.0"
volatile = "0.2.3"
spin = "0.4.6"
uart_16550 = "0.1.0"
x86_64 = "0.2.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"